apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: deploy

on:
  workflow_dispatch:
  push:
    branches:
      - "**"

jobs:
  deploy:
    steps:
      - name: Register deployed artifact
        uses: cloudbees-io/register-deployed-artifact@v2
        with:
          artifact-id: 8aed3b58-86fd-45de-af7c-0647195bd3fa
          target-environment: ap-test
